### ISSUE TITLE
Leak on php7.x (travis-ci pre-build version)

### ISSUE THREAD

**Issue by torden** [torden/php-mdbm#11]
On Travic-ci (precise)
```
=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
MDBM locking [tests/08lock.phpt]
MDBM cache [tests/14cache.phpt]
MDBM replace [tests/16replace.phpt]
=====================================================================
=====================================================================
LEAKED TEST SUMMARY
---------------------------------------------------------------------
MDBM locking [tests/08lock.phpt]
MDBM cache [tests/14cache.phpt]
MDBM replace [tests/16replace.phpt]
=====================================================================
```

**Comment by torden** [comment]
The following result is self-test on ubuntu

*Ubuntu Artful Aardvark, MDBM master branch*
```
#PHP7.0.26
=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   26
---------------------------------------------------------------------

Number of tests :   16                16
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests leaked    :    0 (  0.0%) (  0.0%)
Tests passed    :   16 (100.0%) (100.0%)
---------------------------------------------------------------------
Time taken      :   45 seconds
=====================================================================

#PHP7.1.12
=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   27
---------------------------------------------------------------------

Number of tests :   16                16
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests leaked    :    0 (  0.0%) (  0.0%)
Tests passed    :   16 (100.0%) (100.0%)
---------------------------------------------------------------------
Time taken      :   45 seconds
=====================================================================

#PHP7.2.0
=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   27
---------------------------------------------------------------------

Number of tests :   16                16
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests leaked    :    0 (  0.0%) (  0.0%)
Tests passed    :   16 (100.0%) (100.0%)
---------------------------------------------------------------------
Time taken      :   50 seconds
=====================================================================

```

**Comment by torden** [comment]
The following is reproduce there exception situation.

> Enviroment
---

- VM (VirtualBox)
- Uuntu (12.04.4 LTS, Precise Pangolin)
- PHP 7.0.26
- gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)

- PHP compile (travis's php7.0 build option)
```
Configure Command =>  './configure'  '--with-config-file-path=/home/travis/.phpenv/versions/7.0.26/etc' '--with-config-file-scan-dir=/home/travis/.phpenv/versions/7.0.26/etc/conf.d' '--prefix=/home/travis/.phpenv/versions/7.0.26' '--libexecdir=/home/travis/.phpenv/versions/7.0.26/libexec' '--enable-intl' '--with-openssl' '--without-pear' '--with-gd' '--with-jpeg-dir=/usr' '--with-png-dir=/usr' '--with-freetype-dir=/usr' '--with-freetype' '--enable-exif' '--enable-zip' '--with-zlib' '--with-zlib-dir=/usr' '--with-mcrypt=/usr' '--with-pdo-sqlite' '--enable-soap' '--enable-xmlreader' '--with-xsl' '--enable-ftp' '--with-tidy' '--with-xmlrpc' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-shmop' '--with-mysql=mysqlnd' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--enable-pcntl' '--with-readline' '--enable-mbstring' '--with-curl' '--with-pgsql' '--with-pdo-pgsql' '--with-gettext' '--enable-sockets' '--with-bz2' '--enable-bcmath' '--enable-calendar' '--with-libdir=lib' '--enable-fpm' '--enable-maintainer-zts' '--with-gmp' '--with-kerberos' '--with-imap' '--with-imap-ssl' '--enable-dba' '--with-cdb' '--with-inifile' 
```

> Test on travis-ci's prebuild php7.0.tgz from s3
```
=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   59
---------------------------------------------------------------------

Number of tests :   16                16
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests leaked    :    3 ( 18.8%) ( 18.8%)
Tests passed    :   13 ( 81.2%) ( 81.2%)
---------------------------------------------------------------------
Time taken      :  145 seconds
=====================================================================

=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
MDBM locking [tests/08lock.phpt]
MDBM cache [tests/14cache.phpt]
MDBM replace [tests/16replace.phpt]
=====================================================================

=====================================================================
LEAKED TEST SUMMARY
---------------------------------------------------------------------
MDBM locking [tests/08lock.phpt]
MDBM cache [tests/14cache.phpt]
MDBM replace [tests/16replace.phpt]
=====================================================================
```

> backtrace (whole coredump)
```(gdb) list
590                     EG(exception) || !call->func ||
591                     !(call->func->common.fn_flags & ZEND_ACC_HAS_RETURN_TYPE) ||
592                     zend_verify_internal_return_type(call->func, EX_VAR(opline->result.var)));
593     #endif
594
595             EG(current_execute_data) = call->prev_execute_data;
596             zend_vm_stack_free_args(call);
597             zend_vm_stack_free_call_frame(call);
598
599             if (!RETURN_VALUE_USED(opline)) {
(gdb) bt
#0  0x00000000009431ae in ZEND_DO_ICALL_SPEC_HANDLER (execute_data=0xf5aa080) at /tmp/php-build/source/7.0.26/Zend/zend_vm_execute.h:595
#1  0x0000000000932ca0 in execute_ex (ex=<optimized out>) at /tmp/php-build/source/7.0.26/Zend/zend_vm_execute.h:417
#2  0x000000000098b707 in zend_execute (op_array=<optimized out>, return_value=<optimized out>) at /tmp/php-build/source/7.0.26/Zend/zend_vm_execute.h:458
#3  0x00000000008efc54 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /tmp/php-build/source/7.0.26/Zend/zend.c:1445
#4  0x0000000000882896 in php_execute_script (primary_file=0x7fefff160) at /tmp/php-build/source/7.0.26/main/main.c:2518
#5  0x000000000098d46e in do_cli (argc=68, argv=0xe9a8b60) at /tmp/php-build/source/7.0.26/sapi/cli/php_cli.c:977
#6  0x0000000000454d85 in main (argc=68, argv=0xe9a8b60) at /tmp/php-build/source/7.0.26/sapi/cli/php_cli.c:1347

```
> Test on same version, compile option (added --enable-debug option)
```

=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   59
---------------------------------------------------------------------

Number of tests :   16                16
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests leaked    :    0 (  0.0%) (  0.0%)
Tests passed    :   16 (100.0%) (100.0%)
---------------------------------------------------------------------
Time taken      :  188 seconds
=====================================================================
````

**Comment by torden** [comment]
On now, 
I can't perfectly understand it.  just need more time for analyze..
Fortunately, I can re-produce this issue in my vm

**Comment by torden** [comment]
Fixed
